import type { Locale } from "@/lib/i18n/translations";
import { getDashboardNotification } from "@/lib/i18n/dashboard-copy";

export function getApplicationLabels(locale: Locale) {
  const notification = (key: Parameters<typeof getDashboardNotification>[0]) =>
    getDashboardNotification(key, locale);

  if (locale === "ru") {
    return {
      pageEyebrow: "Заявки",
      pageTitle: "Заявки",
      pageDescription: "Просмотр и управление заявками на статус артиста.",
      loadFailed: "Не удалось загрузить заявки",
      categoriesLoadFailed: "Не удалось загрузить категории",
      detailLoadFailed: "Не удалось загрузить детали заявки",
      approvedToast: notification("applicationApproved"),
      approveFailed: "Не удалось подтвердить заявку",
      rejectedToast: notification("applicationRejected"),
      rejectFailed: "Не удалось отклонить заявку",
      alreadyProcessed: "Заявка уже обработана",
      approveDialogTitle: "Подтвердить заявку",
      approveDialogMessage: (id: string) => `Подтвердить заявку ${id}?`,
      rejectDialogTitle: (id: string) => `Отклонить заявку ${id}`,
      approveAction: "Подтвердить",
      rejectAction: "Отклонить",
      cancelAction: "Отмена",
      closeAction: "Закрыть",
      submitting: "Выполняется...",
      requiredField: "Обязательное поле",
      reason: "Причина",
      searchPlaceholder: "Поиск...",
      categoryAll: "Категория: Все",
      dateAll: "Дата: Все",
      today: "Сегодня",
      week: "7 дней",
      month: "30 дней",
      custom: "Период",
      reset: "Сбросить",
      filterSettings: "Настройки фильтра",
      tableApplication: "Заявка",
      tableCategory: "Категория",
      tableStatus: "Статус",
      tableSubmittedAt: "Время отправки",
      tableContact: "Контакт",
      tableActions: "Действия",
      contactAction: "Связаться",
      viewAction: "Просмотр",
      actionsLabel: "Действия",
      idLabel: "Public ID",
      photoIdLabel: "ID фото",
      subLabel: "Sub",
      drawerTitle: (id: string) => `Заявка ${id}`,
      infoTab: "Информация",
      servicesTab: "Услуги",
      mainInfo: "Основная информация",
      submissionInfo: "Данные заявки",
      contactInfo: "Контактные данные",
      locationInfo: "Местоположение",
      directionInfo: "Категории",
      applicationId: "Public ID заявки",
      userId: "Public ID пользователя",
      profilePhotoId: "ID фотографии",
      topArtist: "Топ-артист",
      yes: "Да",
      no: "Нет",
      region: "Область",
      district: "Район",
      user: "Пользователь",
      createdAt: "Дата создания",
      albumsCount: "Количество альбомов",
      administrator: "Администратор",
      category: "Категория",
      subcategory: "Подкатегория",
      rejectionReason: "Причина отклонения",
      bio: "Bio",
      showLess: "Меньше",
      showMore: "Больше",
      servicesLoading: "Услуги загружаются...",
      servicesLoadFailed: "Не удалось загрузить услуги",
      servicesEmpty: "Услуги не найдены",
      servicesTitle: "Услуги",
      serviceFallback: "Услуга",
      servicePrice: "Цена",
      serviceNote: "Примечание",
      contactTitle: "Контакт",
      primaryPhone: "Основной телефон",
      extraPhone: "Дополнительный телефон",
      adminPhone: "Телефон администратора",
      email: "Email",
      address: "Адрес",
      copyValue: (label: string) => `Скопировать значение: ${label}`,
    };
  }

  return {
    pageEyebrow: "Arizalar",
    pageTitle: "Arizalar",
    pageDescription: "Artist bo'lish uchun yuborilgan arizalarni ko'rish va boshqarish.",
    loadFailed: "Arizalar yuklanmadi",
    categoriesLoadFailed: "Kategoriyalar yuklanmadi",
    detailLoadFailed: "Ariza tafsilotlari yuklanmadi",
    approvedToast: notification("applicationApproved"),
    approveFailed: "Tasdiqlash bajarilmadi",
    rejectedToast: notification("applicationRejected"),
    rejectFailed: "Rad etish bajarilmadi",
    alreadyProcessed: "Ariza allaqachon ko'rib chiqilgan",
    approveDialogTitle: "Arizani tasdiqlash",
    approveDialogMessage: (id: string) => `Ariza ${id} tasdiqlansinmi?`,
    rejectDialogTitle: (id: string) => `Ariza ${id} rad etish`,
    approveAction: "Tasdiqlash",
    rejectAction: "Rad etish",
    cancelAction: "Bekor qilish",
    closeAction: "Yopish",
    submitting: "Bajarilmoqda...",
    requiredField: "Majburiy maydon",
    reason: "Sabab",
    searchPlaceholder: "Qidirish...",
    categoryAll: "Kategoriya: Barchasi",
    dateAll: "Sana: Barchasi",
    today: "Bugun",
    week: "7 kun",
    month: "30 kun",
    custom: "Oraliq",
    reset: "Tozalash",
    filterSettings: "Filter sozlamalari",
    tableApplication: "Ariza",
    tableCategory: "Kategoriya",
    tableStatus: "Holat",
    tableSubmittedAt: "Yuborilgan vaqt",
    tableContact: "Aloqa",
    tableActions: "Amallar",
    contactAction: "Aloqa",
    viewAction: "Ko'rish",
    actionsLabel: "Amallar",
    idLabel: "Public ID",
    photoIdLabel: "Rasm ID",
    subLabel: "Sub",
    drawerTitle: (id: string) => `Ariza ${id}`,
    infoTab: "Ma'lumot",
    servicesTab: "Xizmatlar",
    mainInfo: "Asosiy ma'lumotlar",
    submissionInfo: "Ariza ma'lumotlari",
    contactInfo: "Aloqa ma'lumotlari",
    locationInfo: "Joylashuv",
    directionInfo: "Yo'nalishlar",
    applicationId: "Ariza Public ID",
    userId: "Foydalanuvchi Public ID",
    profilePhotoId: "Rasm ID",
    topArtist: "Top artist",
    yes: "Ha",
    no: "Yo'q",
    region: "Viloyat",
    district: "Tuman",
    user: "Foydalanuvchi",
    createdAt: "Yaratilgan vaqt",
    albumsCount: "Albomlar soni",
    administrator: "Administrator",
    category: "Kategoriya",
    subcategory: "Subkategoriya",
    rejectionReason: "Rad etish sababi",
    bio: "Bio",
    showLess: "Kamroq",
    showMore: "Ko'proq",
    servicesLoading: "Xizmatlar yuklanmoqda...",
    servicesLoadFailed: "Xizmatlar yuklanmadi",
    servicesEmpty: "Xizmatlar topilmadi",
    servicesTitle: "Xizmatlar",
    serviceFallback: "Xizmat",
    servicePrice: "Narxi",
    serviceNote: "Izoh",
    contactTitle: "Aloqa",
    primaryPhone: "Telefon asosiy",
    extraPhone: "Qo'shimcha telefon",
    adminPhone: "Administrator telefoni",
    email: "Email",
    address: "Manzil",
    copyValue: (label: string) => `${label} qiymatini nusxalash`,
  };
}

export type ApplicationLabels = ReturnType<typeof getApplicationLabels>;
