import type { Locale } from "@/lib/i18n/translations";

export function getApplicationLabels(locale: Locale) {
  if (locale === "ru") {
    return {
      pageEyebrow: "Заявки",
      pageTitle: "Заявки",
      pageDescription: "Просмотр и управление заявками на статус артиста.",
      loadFailed: "Не удалось загрузить заявки",
      categoriesLoadFailed: "Не удалось загрузить категории",
      detailLoadFailed: "Не удалось загрузить детали заявки",
      approvedToast: "Заявка подтверждена",
      approveFailed: "Не удалось подтвердить заявку",
      rejectedToast: "Заявка отклонена",
      rejectFailed: "Не удалось отклонить заявку",
      alreadyProcessed: "Заявка уже обработана",
      approveDialogTitle: "Подтвердить заявку",
      approveDialogMessage: (id: string) => `Подтвердить заявку #${id}?`,
      rejectDialogTitle: (id: string) => `Отклонить заявку #${id}`,
      approveAction: "Подтвердить",
      rejectAction: "Отклонить",
      cancelAction: "Отмена",
      closeAction: "Закрыть",
      submitting: "Выполняется...",
      requiredField: "Обязательное поле",
      reason: "Причина",
      searchPlaceholder: "Поиск...",
      categoryAll: "Категория: Все",
      dateAll: "Дата: Все",
      today: "Сегодня",
      week: "7 дней",
      month: "30 дней",
      custom: "Период",
      reset: "Сбросить",
      filterSettings: "Настройки фильтра",
      tableApplication: "Заявка",
      tableCategory: "Категория",
      tableStatus: "Статус",
      tableSubmittedAt: "Время отправки",
      tableContact: "Контакт",
      tableActions: "Действия",
      contactAction: "Связаться",
      viewAction: "Просмотр",
      actionsLabel: "Действия",
      idLabel: "ID",
      photoIdLabel: "Photo ID",
      subLabel: "Sub",
      drawerTitle: (id: string) => `Заявка #${id}`,
      infoTab: "Информация",
      servicesTab: "Услуги",
      mainInfo: "Основная информация",
      user: "Пользователь",
      createdAt: "Дата создания",
      albumsCount: "Количество альбомов",
      administrator: "Администратор",
      category: "Категория",
      subcategory: "Подкатегория",
      rejectionReason: "Причина отклонения",
      bio: "Bio",
      showLess: "Меньше",
      showMore: "Больше",
      servicesLoading: "Услуги загружаются...",
      servicesLoadFailed: "Не удалось загрузить услуги",
      servicesEmpty: "Услуги не найдены",
      servicesTitle: "Услуги",
      contactTitle: "Контакт",
      primaryPhone: "Основной телефон",
      extraPhone: "Дополнительный телефон",
      adminPhone: "Телефон администратора",
      email: "Email",
      address: "Адрес",
      copyValue: (label: string) => `Скопировать значение: ${label}`,
    };
  }

  return {
    pageEyebrow: "Arizalar",
    pageTitle: "Arizalar",
    pageDescription: "Artist bo'lish uchun yuborilgan arizalarni ko'rish va boshqarish.",
    loadFailed: "Arizalar yuklanmadi",
    categoriesLoadFailed: "Kategoriyalar yuklanmadi",
    detailLoadFailed: "Ariza tafsilotlari yuklanmadi",
    approvedToast: "Ariza tasdiqlandi",
    approveFailed: "Tasdiqlash bajarilmadi",
    rejectedToast: "Ariza rad etildi",
    rejectFailed: "Rad etish bajarilmadi",
    alreadyProcessed: "Ariza allaqachon ko'rib chiqilgan",
    approveDialogTitle: "Arizani tasdiqlash",
    approveDialogMessage: (id: string) => `Ariza #${id} tasdiqlansinmi?`,
    rejectDialogTitle: (id: string) => `Ariza #${id} rad etish`,
    approveAction: "Tasdiqlash",
    rejectAction: "Rad etish",
    cancelAction: "Bekor qilish",
    closeAction: "Yopish",
    submitting: "Bajarilmoqda...",
    requiredField: "Majburiy maydon",
    reason: "Sabab",
    searchPlaceholder: "Qidirish...",
    categoryAll: "Kategoriya: Barchasi",
    dateAll: "Sana: Barchasi",
    today: "Bugun",
    week: "7 kun",
    month: "30 kun",
    custom: "Oraliq",
    reset: "Tozalash",
    filterSettings: "Filter sozlamalari",
    tableApplication: "Ariza",
    tableCategory: "Kategoriya",
    tableStatus: "Holat",
    tableSubmittedAt: "Yuborilgan vaqt",
    tableContact: "Aloqa",
    tableActions: "Amallar",
    contactAction: "Aloqa",
    viewAction: "Ko'rish",
    actionsLabel: "Amallar",
    idLabel: "ID",
    photoIdLabel: "Photo ID",
    subLabel: "Sub",
    drawerTitle: (id: string) => `Ariza #${id}`,
    infoTab: "Ma'lumot",
    servicesTab: "Xizmatlar",
    mainInfo: "Asosiy ma'lumotlar",
    user: "Foydalanuvchi",
    createdAt: "Yaratilgan vaqt",
    albumsCount: "Albomlar soni",
    administrator: "Administrator",
    category: "Kategoriya",
    subcategory: "Subkategoriya",
    rejectionReason: "Rad etish sababi",
    bio: "Bio",
    showLess: "Kamroq",
    showMore: "Ko'proq",
    servicesLoading: "Xizmatlar yuklanmoqda...",
    servicesLoadFailed: "Xizmatlar yuklanmadi",
    servicesEmpty: "Xizmatlar topilmadi",
    servicesTitle: "Xizmatlar",
    contactTitle: "Aloqa",
    primaryPhone: "Telefon asosiy",
    extraPhone: "Qo'shimcha telefon",
    adminPhone: "Administrator telefoni",
    email: "Email",
    address: "Manzil",
    copyValue: (label: string) => `${label} qiymatini nusxalash`,
  };
}

export type ApplicationLabels = ReturnType<typeof getApplicationLabels>;
